name: 🐛 Bug Report
description: Report a bug or issue with Party Gallery
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.
        
        ⚠️ **Note**: This is proprietary software. Please ensure you have proper authorization to report issues.

  - type: checkboxes
    id: cla-signed
    attributes:
      label: Legal Compliance
      description: Confirm you have proper authorization
      options:
        - label: I have signed the required CLA and have authorization to report issues
          required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform is affected?
      options:
        - Android
        - iOS
        - Web
        - Desktop
        - Multiple platforms
        - Shared module
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App Version
      description: What version of the app are you using?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "Describe what should happen..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "Describe what actually happened..."
    validations:
      required: true

  - type: dropdown
    id: party-context
    attributes:
      label: Party Context
      description: What party feature is affected?
      options:
        - Authentication/Login
        - SignUp Flow
        - Party Events
        - Media Upload/Sharing
        - Party Chat
        - Profile Management
        - Party Feed
        - Party Studio
        - Party Discovery
        - Party Recommendations
        - Other
    validations:
      required: false

  - type: textarea
    id: device-info
    attributes:
      label: Device Information
      description: Device and system information
      placeholder: |
        - Device: [e.g., iPhone 12, Samsung Galaxy S21, MacBook Pro]
        - OS: [e.g., iOS 15.1, Android 12, macOS 12.1, Windows 11]
        - Browser: [e.g., Chrome 96, Safari 15] (for web)
        - Screen resolution: [e.g., 1920x1080]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Console Output
      description: Any relevant error messages or console output
      render: shell
      placeholder: "Paste error logs here..."

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: Add screenshots or videos to help explain the problem
      placeholder: "Drag and drop images/videos here or paste links..."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: "Add any other relevant information..."