name: Dependency Update
on:
  schedule:
    - cron: '0 9 * * 1' # Lunes a las 9 AM UTC
  workflow_dispatch:

jobs:
  gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Update Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      
      - name: Generate Gradle Wrapper
        run: ./gradlew wrapper --gradle-version=latest
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update Gradle wrapper"
          title: "🔧 Update Gradle Wrapper"
          body: |
            ## 🔧 Gradle Wrapper Update
            
            This PR updates the Gradle wrapper to the latest version.
            
            ### Changes:
            - Updated `gradle/wrapper/gradle-wrapper.properties`
            - Updated `gradle/wrapper/gradle-wrapper.jar`
            - Updated `gradlew` and `gradlew.bat`
            
            Auto-generated by GitHub Actions.
          branch: update/gradle-wrapper